### PR TITLE
Updates to get it working in 2022

### PR DESCRIPTION
**Pull request by tobybell**
Hi oknuutti, 

Not sure if this is a useful pull request for you, but sharing just in case. These were changes I had to make to get this project running on my Mac in 2022 using regular a Python 3.10 installation. Feel free to accept these changes to make it easier for others in the future, or just accept a subset of them, etc.

### CODE REVIEW

**Comment by oknuutti** [comment]
Hi Toby,

Thanks for the pull request!

Sorry for the state of the code, it was written fast and hacked many times to support research in different directions. I hope you'll be able to find some usage of it. If after some trying you can't seem to get something to work, do contact me.

**Comment by tobybell** [comment]
Great!

I don’t know if you saw, I also was not able to access the data folder on Google drive. i didn’t have permission. I tried “request access” through Google, but I don’t know if you got that message.

EDIT: Oh, you shared it! Thank you!

**Comment by tobybell** [comment]
I got your data directory, but it seems like it doesn't have all the models referenced by the code. I'm trying the "rose" and "orex" missions, and it seems to need models for P67 and Bennu that aren't in the data directory you shared. Do you know if you have additional data elsewhere?

I'm especially interested in your particle model, so if you know a particular mission/case I could pass to the `batch1.py` script to render something with particles, that would be great. Thank you!

**Comment by oknuutti** [comment]
I updated the 67P files, however, I commented out the texture file as the results are not very good with it. I couldn't find the Bennu files now. Anyway, it should be possible to generate them by downloading the 3d model from e.g. https://www.asteroidmission.org/updated-bennu-shape-model-3d-files/ and then checking that the model is given in km. I used Blender to possibly scale the models and to reduce the number of vertices for the simplified 3d models that have 1000, 4000, and 16000 vertices. A high-vertex model for 67P can be downloaded from http://mattias.malmer.nu/category/rosetta/ .

There is code that approximates particles by assuming that they emit light in proportion to their density. Rendered depthmap of the scene is used to block the light that would have originated from the other side of the asteroid. However, shadowing effects are not modeled. The particle density distribution is given as an exr-file and such files can be generated using another project at https://github.com/SISPO-developers/ComaCreator, which in turn is related to Blender and raytracing based scene rendering project https://github.com/SISPO-developers/sispo. There's also an interface there to access the rendering implemented in this project.

**Pull request merged**
